package com.serverless.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.time.Year;
import java.util.List;

@DynamoDBTable(tableName = "livros")
public class Livro {

    private String id;
    private String titulo;
    private Year anoLancamento;
    private List<TipoDeLivro> tipoDeLivro;
    private Genero genero;

    public Livro() {
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "titulo")
    public String getTitulo() {
        return titulo;
    }
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @DynamoDBAttribute(attributeName = "anoDeLancamento")
    public Year getAnoLancamento() {
        return anoLancamento;
    }
    public void setAnoLancamento(Year anoLancamento) {
        this.anoLancamento = anoLancamento;
    }

    @DynamoDBAttribute(attributeName = "tipoDeLivro")
    public List<TipoDeLivro> getTipoDeLivro() {
        return tipoDeLivro;
    }
    public void setTipoDeLivro(List<TipoDeLivro> tipoDeLivro) {
        this.tipoDeLivro = tipoDeLivro;
    }

    @DynamoDBAttribute(attributeName = "genero")
    public Genero getGenero() {
        return genero;
    }
    public void setGenero(Genero genero) {
        this.genero = genero;
    }
}
